name: anime_update_panel
description: Anime Update Panel
publish_to: 'none'
version: 1.0.6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fluent_ui: ^4.8.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  window_manager: ^0.3.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
